// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.2.0
// source: mycachepb.proto

package mycachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_mycachepb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_mycachepb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_mycachepb_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Request) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVResponse) Reset() {
	*x = KVResponse{}
	mi := &file_mycachepb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVResponse) ProtoMessage() {}

func (x *KVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mycachepb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVResponse.ProtoReflect.Descriptor instead.
func (*KVResponse) Descriptor() ([]byte, []int) {
	return file_mycachepb_proto_rawDescGZIP(), []int{1}
}

func (x *KVResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type InfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KeysNum          int64                  `protobuf:"varint,1,opt,name=keysNum,proto3" json:"keysNum,omitempty"`
	CurrentUsedBytes int64                  `protobuf:"varint,2,opt,name=current_used_bytes,json=currentUsedBytes,proto3" json:"current_used_bytes,omitempty"`
	MaxUsedBytes     int64                  `protobuf:"varint,3,opt,name=max_used_bytes,json=maxUsedBytes,proto3" json:"max_used_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_mycachepb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mycachepb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_mycachepb_proto_rawDescGZIP(), []int{2}
}

func (x *InfoResponse) GetKeysNum() int64 {
	if x != nil {
		return x.KeysNum
	}
	return 0
}

func (x *InfoResponse) GetCurrentUsedBytes() int64 {
	if x != nil {
		return x.CurrentUsedBytes
	}
	return 0
}

func (x *InfoResponse) GetMaxUsedBytes() int64 {
	if x != nil {
		return x.MaxUsedBytes
	}
	return 0
}

var File_mycachepb_proto protoreflect.FileDescriptor

const file_mycachepb_proto_rawDesc = "" +
	"\n" +
	"\x0fmycachepb.proto\x12\tmycachepb\"1\n" +
	"\aRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\"\n" +
	"\n" +
	"KVResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"|\n" +
	"\fInfoResponse\x12\x18\n" +
	"\akeysNum\x18\x01 \x01(\x03R\akeysNum\x12,\n" +
	"\x12current_used_bytes\x18\x02 \x01(\x03R\x10currentUsedBytes\x12$\n" +
	"\x0emax_used_bytes\x18\x03 \x01(\x03R\fmaxUsedBytes2>\n" +
	"\n" +
	"GroupCache\x120\n" +
	"\x03Get\x12\x12.mycachepb.Request\x1a\x15.mycachepb.KVResponseB\x0eZ\f./;mycachepbb\x06proto3"

var (
	file_mycachepb_proto_rawDescOnce sync.Once
	file_mycachepb_proto_rawDescData []byte
)

func file_mycachepb_proto_rawDescGZIP() []byte {
	file_mycachepb_proto_rawDescOnce.Do(func() {
		file_mycachepb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mycachepb_proto_rawDesc), len(file_mycachepb_proto_rawDesc)))
	})
	return file_mycachepb_proto_rawDescData
}

var file_mycachepb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mycachepb_proto_goTypes = []any{
	(*Request)(nil),      // 0: mycachepb.Request
	(*KVResponse)(nil),   // 1: mycachepb.KVResponse
	(*InfoResponse)(nil), // 2: mycachepb.InfoResponse
}
var file_mycachepb_proto_depIdxs = []int32{
	0, // 0: mycachepb.GroupCache.Get:input_type -> mycachepb.Request
	1, // 1: mycachepb.GroupCache.Get:output_type -> mycachepb.KVResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mycachepb_proto_init() }
func file_mycachepb_proto_init() {
	if File_mycachepb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mycachepb_proto_rawDesc), len(file_mycachepb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mycachepb_proto_goTypes,
		DependencyIndexes: file_mycachepb_proto_depIdxs,
		MessageInfos:      file_mycachepb_proto_msgTypes,
	}.Build()
	File_mycachepb_proto = out.File
	file_mycachepb_proto_goTypes = nil
	file_mycachepb_proto_depIdxs = nil
}
